import Navbar from "../Components/Navbar.jsx"
import Home from "./Home.jsx"
import Project from "./Project.jsx"
import CreatePost from "./CreatePost.jsx"
import UploadProject from "./UploadProject.jsx"
import AboutUs from "./AboutUs.jsx"
import CalendarPage from "./CalendarPage.jsx"
import ProjectDetails from "./ProjectDetails.jsx"
import Login from "./Login.jsx"
export {Navbar, Home, Project ,CreatePost,UploadProject, AboutUs,CalendarPage,ProjectDetails,Login}